"""Type stubs for the compiled core ``fqxv._fqxv``.

Hand-maintained to mirror ``crates/fqxv-python/src/lib.rs``; keep them in sync when
the binding surface changes. The pure-Python ``fqxv`` package re-exports every name
here, so this is what a type checker sees for ``import fqxv``.
"""

import os
from typing import List, Optional, Protocol, Sequence, Tuple, Union, final

# A path or in-memory archive: what the seekable entry points (inspect, open_index,
# read_*, verify) accept.
StrOrBytesPath = Union[str, "os.PathLike[str]", bytes]

class _Readable(Protocol):
    """Any file-like object with a byte ``read`` (e.g. an ``http.client`` response)."""

    def read(self, n: int = ..., /) -> bytes: ...

# The streaming entry points (open, decompress_*) additionally accept a file-like.
ReadSource = Union[StrOrBytesPath, _Readable]

class FqxvError(Exception):
    """Base error for fqxv archive failures (corrupt/unsupported archives)."""

@final
class Record:
    """One decoded FASTQ record. ``name`` excludes the leading ``@``; ``sequence``
    and ``quality`` are raw bytes with no line endings."""

    @property
    def name(self) -> bytes: ...
    @property
    def sequence(self) -> bytes: ...
    @property
    def quality(self) -> bytes: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Reader:
    """A streaming iterator over an archive's records, in original file order."""

    def __iter__(self) -> "Reader": ...
    def __next__(self) -> Record: ...
    def __enter__(self) -> "Reader": ...
    def __exit__(self, *args: object) -> bool: ...

@final
class Info:
    """Archive metadata from the header and footer index (no payload decode)."""

    @property
    def reads(self) -> int: ...
    @property
    def blocks(self) -> int: ...
    @property
    def group_size(self) -> int: ...
    @property
    def reordered(self) -> bool: ...
    @property
    def keep_order(self) -> bool: ...
    @property
    def regenerated_names(self) -> bool: ...
    @property
    def plus_normalized(self) -> bool: ...
    @property
    def format_version(self) -> int: ...
    @property
    def seq_order(self) -> int: ...
    @property
    def quality_binning(self) -> int: ...
    @property
    def names_bytes(self) -> int: ...
    @property
    def sequence_bytes(self) -> int: ...
    @property
    def quality_bytes(self) -> int: ...
    @property
    def platform(self) -> str: ...
    @property
    def whole_file_crc(self) -> Optional[int]: ...
    @property
    def member_labels(self) -> List[str]: ...
    @property
    def required_features(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class GroupLoc:
    """On-disk location of one row group."""

    @property
    def block_offset(self) -> int: ...
    @property
    def read_count(self) -> int: ...

@final
class Index:
    """A parsed footer row-group index (plain layout only)."""

    @property
    def total_reads(self) -> int: ...
    @property
    def whole_file_crc(self) -> int: ...
    @property
    def num_groups(self) -> int: ...
    def groups(self) -> List[GroupLoc]: ...
    def stream_range(self, group: int, stream: str) -> Tuple[int, int]: ...
    def stream_crc(self, group: int, stream: str) -> int: ...
    def verify_stream(self, group: int, stream: str, coded: bytes) -> None: ...
    def __repr__(self) -> str: ...

@final
class Estimate:
    """Projected compression of a FASTQ from coding a bounded leading sample."""

    @property
    def sample_reads(self) -> int: ...
    @property
    def sample_bases(self) -> int: ...
    @property
    def raw_bytes(self) -> int: ...
    @property
    def names_bytes(self) -> int: ...
    @property
    def sequence_bytes(self) -> int: ...
    @property
    def quality_bytes(self) -> int: ...
    @property
    def archive_bytes(self) -> int: ...
    @property
    def exhausted(self) -> bool: ...
    @property
    def platform(self) -> str: ...
    @property
    def ratio(self) -> float: ...
    def __repr__(self) -> str: ...

# --- Whole-archive / streaming / projection ---------------------------------- #
def open(source: ReadSource, *, threads: int = ...) -> Reader: ...
def decompress_to_path(
    source: ReadSource, dest: StrOrBytesPath, *, threads: int = ...
) -> int: ...
def decompress_to_bytes(source: ReadSource, *, threads: int = ...) -> bytes: ...
def inspect(source: StrOrBytesPath) -> Info: ...
def open_index(source: StrOrBytesPath) -> Index: ...
def read_names(
    source: StrOrBytesPath, groups: Optional[Sequence[int]] = ...
) -> List[bytes]: ...
def read_sequences(
    source: StrOrBytesPath, groups: Optional[Sequence[int]] = ...
) -> List[bytes]: ...
def read_qualities(
    source: StrOrBytesPath, groups: Optional[Sequence[int]] = ...
) -> List[bytes]: ...
def read_block(source: StrOrBytesPath, group: int) -> List[Record]: ...
def estimate(
    source: Union[StrOrBytesPath, Sequence[StrOrBytesPath]],
    *,
    level: int = ...,
    quality_binning: str = ...,
    sample_reads: int = ...,
    threads: int = ...,
) -> Estimate: ...
def verify(source: StrOrBytesPath, *, threads: int = ...) -> None: ...

# --- Random-access primitives for the remote (HTTP Range) reader ------------- #
def parse_index_suffix(
    suffix: bytes, file_len: int
) -> Tuple[Optional[Index], Optional[int]]: ...
def decode_names_bytes(coded: bytes) -> List[bytes]: ...
def decode_sequences_bytes(coded: bytes) -> List[bytes]: ...
def decode_qualities_bytes(coded: bytes, seq: Optional[bytes] = ...) -> List[bytes]: ...
def quality_needs_sequence_bytes(coded: bytes) -> bool: ...
